[package]
name = "alor_api_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
ureq = "2.9.6"
typed-builder = "0.18.1"
thiserror = "1.0.58"
mockito = "1.4.0"
serde_urlencoded = "0.7.1"